/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AssessmentQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AssessmentQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "CompetitionQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "CompetitionQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "DownloadQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "DownloadQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MarketAnalysisQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MarketAnalysisQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MasterDataCallDownStreamHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "NewsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "NewsQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "OpenAIApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VectorStoreBatchFlow": {
      "arn": string
      "type": "sst.aws.StepFunctions"
    }
    "VectorStoreCheckBatch": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WeaviateAPIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WeaviateCollectionCreator": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}